# Generated by Django 6.1.1 on 2026-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Summary of the experiment or article')),
                ('python_notebook', models.FileField(blank=True, null=True, upload_to='articles/notebooks/')),
                ('experimental_results', models.FileField(blank=True, null=True, upload_to='articles/results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication_type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Workshop', 'Workshop')], max_length=50)),
                ('is_best_paper', models.BooleanField(default=False)),
                ('abstract', models.TextField()),
                ('bibtex_file', models.FileField(blank=True, null=True, upload_to='publications/bibtex/')),
                ('poster_file', models.FileField(blank=True, null=True, upload_to='publications/posters/')),
                ('date_published', models.DateField()),
            ],
        ),
    ]
