# Generated by Django 6.1.1 on 2026-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., Doctor of Philosophy - PhD, Computer Science', max_length=200)),
                ('institution', models.CharField(help_text='e.g., Tezpur University, Assam', max_length=200)),
                ('start_year', models.CharField(help_text='e.g., 2023', max_length=10)),
                ('end_year', models.CharField(default='Present', help_text="Year or 'Present'", max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional details about your thesis or coursework', null=True)),
            ],
        ),
    ]
