# Generated by Django 6.1.1 on 2026-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='e.g., Teaching Associate', max_length=200)),
                ('organization', models.CharField(help_text='e.g., Gauhati University', max_length=200)),
                ('duration', models.CharField(help_text='e.g., August 2023 - November 2023', max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g., Guwahati, Assam, India', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Details about your role or project', null=True)),
            ],
        ),
    ]
