# Generated by Django 6.1.1 on 2026-09-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., UGC NET Certificate', max_length=200)),
                ('issue_date', models.CharField(help_text='e.g., December 2022', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional details about the exam or course', null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Optional PDF or image of the certificate', null=True, upload_to='certifications/')),
            ],
        ),
    ]
